# Generated by Django 2.0.9 on 2019-01-09 17:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Convite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255)),
                ('telefone', models.CharField(max_length=15)),
                ('nome_empresa', models.CharField(max_length=255)),
                ('imagem', models.ImageField(default='perfil/user.png', upload_to='perfil')),
                ('bloqueados', models.ManyToManyField(related_name='_perfil_bloqueados_+', to='perfis.Perfil')),
                ('contatos', models.ManyToManyField(related_name='_perfil_contatos_+', to='perfis.Perfil')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Postagem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField()),
                ('data', models.DateTimeField(auto_now=True)),
                ('privacidade', models.CharField(choices=[('PUBLIC', 'Público'), ('FRIENDS', 'Amigos'), ('PRIVATE', 'Somente eu')], default='PUBLIC', max_length=10)),
                ('imagem', models.ImageField(null=True, upload_to='postagem')),
            ],
            options={
                'ordering': ['-data'],
            },
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=20)),
                ('animation', models.CharField(default='', max_length=20)),
                ('color', models.CharField(default='#CCC', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Partilhamento',
            fields=[
                ('postagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perfis.Postagem')),
            ],
            bases=('perfis.postagem',),
        ),
        migrations.AddField(
            model_name='reaction',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.Postagem'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.ReactionType'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='perfil',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timeline', to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='reactions',
            field=models.ManyToManyField(through='perfis.Reaction', to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='convite',
            name='convidado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_recebidos', to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='convite',
            name='solicitante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites_feitos', to='perfis.Perfil'),
        ),
        migrations.AddField(
            model_name='partilhamento',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partilhamentos', to='perfis.Postagem'),
        ),
    ]
