# Generated by Django 2.1.3 on 2019-01-06 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0003_postagem'),
    ]

    operations = [
        migrations.CreateModel(
            name='Partilhamento',
            fields=[
                ('postagem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='perfis.Postagem')),
            ],
            bases=('perfis.postagem',),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('perfil', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.Perfil')),
            ],
        ),
        migrations.CreateModel(
            name='ReactionType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=10)),
                ('icon', models.CharField(max_length=20)),
                ('animation', models.CharField(default='', max_length=20)),
                ('color', models.CharField(default='#CCC', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='postagem',
            name='privacidade',
            field=models.CharField(choices=[('PUBLIC', 'Público'), ('FRIENDS', 'Amigos'), ('PRIVATE', 'Somente eu')], default='PUBLIC', max_length=10),
        ),
        migrations.AddField(
            model_name='reaction',
            name='postagem',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.Postagem'),
        ),
        migrations.AddField(
            model_name='reaction',
            name='tipo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='perfis.ReactionType'),
        ),
        migrations.AddField(
            model_name='partilhamento',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='partilhamentos', to='perfis.Postagem'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='reactions',
            field=models.ManyToManyField(through='perfis.Reaction', to='perfis.Perfil'),
        ),
    ]
