# Generated by Django 2.1.3 on 2019-01-07 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perfis', '0004_auto_20190106_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfil',
            name='imagem',
            field=models.ImageField(default='perfil/user.png', upload_to='perfil'),
        ),
        migrations.AddField(
            model_name='postagem',
            name='imagem',
            field=models.ImageField(null=True, upload_to='postagem'),
        ),
    ]
